// AUTO-GENERATED by scripts/generate-assets.mjs — do not edit by hand.
// Short content hash of public/og-image.png. It is appended to the social-card
// URL so that when the image changes, the URL changes too, forcing platform
// caches (LinkedIn, X, Facebook, iMessage, Slack) to refetch the new image.
export const OG_IMAGE_VERSION = "6e14dcda";
